<?php

namespace ContainerSsx1TLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\EasyThemesBundle\EventListener\ThemeOptionsListener' shared autowired service.
     *
     * @return \Terminal42\EasyThemesBundle\EventListener\ThemeOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-easy_themes/src/EventListener/ThemeOptionsListener.php';

        return $container->services['Terminal42\\EasyThemesBundle\\EventListener\\ThemeOptionsListener'] = new \Terminal42\EasyThemesBundle\EventListener\ThemeOptionsListener(($container->privates['Terminal42\\EasyThemesBundle\\Helper'] ?? $container->load('getHelperService')));
    }
}
