<?php

namespace ContainerSomrxkp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCallbackSetupListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\ChangeLanguage\EventListener\CallbackSetupListener' shared autowired service.
     *
     * @return \Terminal42\ChangeLanguage\EventListener\CallbackSetupListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-changelanguage/src/EventListener/CallbackSetupListener.php';

        return $container->services['Terminal42\\ChangeLanguage\\EventListener\\CallbackSetupListener'] = new \Terminal42\ChangeLanguage\EventListener\CallbackSetupListener();
    }
}
