<?php

namespace ContainerSomrxkp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMissingLanguageIconListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\ChangeLanguage\EventListener\DataContainer\MissingLanguageIconListener' shared autowired service.
     *
     * @return \Terminal42\ChangeLanguage\EventListener\DataContainer\MissingLanguageIconListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-changelanguage/src/EventListener/DataContainer/MissingLanguageIconListener.php';

        return $container->services['Terminal42\\ChangeLanguage\\EventListener\\DataContainer\\MissingLanguageIconListener'] = new \Terminal42\ChangeLanguage\EventListener\DataContainer\MissingLanguageIconListener(($container->services['security.helper'] ?? $container->getSecurity_HelperService()));
    }
}
