<?php

namespace ContainerSomrxkp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPaletteListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\EasyThemesBundle\EventListener\UserPaletteListener' shared autowired service.
     *
     * @return \Terminal42\EasyThemesBundle\EventListener\UserPaletteListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-easy_themes/src/EventListener/UserPaletteListener.php';

        return $container->services['Terminal42\\EasyThemesBundle\\EventListener\\UserPaletteListener'] = new \Terminal42\EasyThemesBundle\EventListener\UserPaletteListener(($container->services['security.helper'] ?? $container->getSecurity_HelperService()));
    }
}
