<?php

namespace ContainerXRMqzeh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleNavigationListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\ChangeLanguage\EventListener\Navigation\ArticleNavigationListener' shared autowired service.
     *
     * @return \Terminal42\ChangeLanguage\EventListener\Navigation\ArticleNavigationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-changelanguage/src/EventListener/Navigation/ArticleNavigationListener.php';

        return $container->services['Terminal42\\ChangeLanguage\\EventListener\\Navigation\\ArticleNavigationListener'] = new \Terminal42\ChangeLanguage\EventListener\Navigation\ArticleNavigationListener(($container->services['contao.security.token_checker'] ?? $container->getContao_Security_TokenCheckerService()));
    }
}
