<?php

namespace ContainerXRMqzeh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelperService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Terminal42\EasyThemesBundle\Helper' shared autowired service.
     *
     * @return \Terminal42\EasyThemesBundle\Helper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-easy_themes/src/Helper.php';

        return $container->privates['Terminal42\\EasyThemesBundle\\Helper'] = new \Terminal42\EasyThemesBundle\Helper(($container->services['security.helper'] ?? $container->getSecurity_HelperService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['contao.routing.scope_matcher'] ?? $container->getContao_Routing_ScopeMatcherService()), ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->services['router'] ?? $container->getRouterService()));
    }
}
