<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRMqzeh\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRMqzeh/Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRMqzeh.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRMqzeh\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false);
}

return new \ContainerXRMqzeh\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer([
    'container.build_hash' => 'XRMqzeh',
    'container.build_id' => 'a300379f',
    'container.build_time' => 1698092251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRMqzeh');
